name: Build L-SMASH

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  win-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        config: 
          - { cpu: i686, arch: x86 }
          - { cpu: x86_64, arch: x64 }
        author: [l-smash, Mr-Ojii, vimeo]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Checkout L-SMASH repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        repository: ${{ matrix.author }}/l-smash
        path: l-smash
    - name: Set REV_LIST_COUNT
      id: rev
      run: |
        cd ${{ github.workspace }}/l-smash
        REVCOUNT=`git rev-list --count HEAD`
        echo "REV_LIST_COUNT=${REVCOUNT}" >> $GITHUB_OUTPUT
    - name: move LICENSE file
      run: |
        cd ${{ github.workspace }}/l-smash
        mv LICENSE cli
    - name: Install mingw-w64
      run: sudo apt install mingw-w64
      
    - name: Build obuparse
      run: |
        cd ${{ github.workspace }}
        git clone https://github.com/dwbuiten/obuparse.git
        cd obuparse
        ${{ matrix.config.cpu }}-w64-mingw32-gcc -c obuparse.c
        ${{ matrix.config.cpu }}-w64-mingw32-ar r obuparse.lib obuparse.o
        
    - name: Build
      run: |
        cd ${{ github.workspace }}/l-smash
        ./configure --cross-prefix=${{ matrix.config.cpu }}-w64-mingw32- --extra-cflags=-I../obuparse --extra-ldflags=-L../obuparse
        make -j$(nproc)
        
    - name: Create archive
      run: |
        cd ${{ github.workspace }}/l-smash/cli
        zip L-SMASH_rev${{ steps.rev.outputs.REV_LIST_COUNT }}_win_${{ matrix.config.arch }}_${{ matrix.author }} LICENSE muxer.exe remuxer.exe boxdumper.exe timelineeditor.exe
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: l-smash-win-${{ matrix.config.arch }}-${{ matrix.author }}
        path: ${{ github.workspace }}/l-smash/cli/L-SMASH_rev${{ steps.rev.outputs.REV_LIST_COUNT }}_win_${{ matrix.config.arch }}_${{ matrix.author }}.zip
    
  linux-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        config: 
          - { option: -m32, arch: x86 }
          - { option: -m64, arch: x64 }
        author: [l-smash, Mr-Ojii, vimeo]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Checkout L-SMASH repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        repository: ${{ matrix.author }}/l-smash
        path: l-smash
    - name: Set REV_LIST_COUNT
      id: rev
      run: |
        cd ${{ github.workspace }}/l-smash
        REVCOUNT=`git rev-list --count HEAD`
        echo "REV_LIST_COUNT=${REVCOUNT}" >> $GITHUB_OUTPUT
    - name: move LICENSE file
      run: |
        cd ${{ github.workspace }}/l-smash
        mv LICENSE cli
    - name: Install multilib
      run: |
        sudo apt update
        sudo apt install gcc-multilib
        
    - name: Build obuparse
      run: |
        cd ${{ github.workspace }}
        git clone https://github.com/dwbuiten/obuparse.git
        cd obuparse
        gcc -c obuparse.c ${{ matrix.config.option }}
        ar r libobuparse.a obuparse.o
        
    - name: Build
      run: |
        cd ${{ github.workspace }}/l-smash
        ./configure --extra-cflags="-I../obuparse ${{ matrix.config.option }}" --extra-ldflags=-L../obuparse
        make -j$(nproc)
    - name: Create archive
      run: |
        cd ${{ github.workspace }}/l-smash/cli
        zip L-SMASH_rev${{ steps.rev.outputs.REV_LIST_COUNT }}_linux_${{ matrix.config.arch }}_${{ matrix.author }} LICENSE muxer remuxer boxdumper timelineeditor
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: l-smash-linux-${{ matrix.config.arch }}-${{ matrix.author }}
        path: ${{ github.workspace }}/l-smash/cli/L-SMASH_rev${{ steps.rev.outputs.REV_LIST_COUNT }}_linux_${{ matrix.config.arch }}_${{ matrix.author }}.zip

  mac-build:
    runs-on: macos-latest
    
    strategy:
      matrix:
        author: [l-smash, Mr-Ojii, vimeo]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Checkout L-SMASH repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        repository: ${{ matrix.author }}/l-smash
        path: l-smash
    - name: Set REV_LIST_COUNT
      id: rev
      run: |
        cd ${{ github.workspace }}/l-smash
        REVCOUNT=`git rev-list --count HEAD`
        echo "REV_LIST_COUNT=${REVCOUNT}" >> $GITHUB_OUTPUT
    - name: move LICENSE file
      run: |
        cd ${{ github.workspace }}/l-smash
        mv LICENSE cli
        
    - name: Build obuparse
      run: |
        cd ${{ github.workspace }}
        git clone https://github.com/dwbuiten/obuparse.git
        cd obuparse
        gcc -c obuparse.c ${{ matrix.config.option }}
        ar r libobuparse.a obuparse.o
        
    - name: Build
      run: |
        cd ${{ github.workspace }}/l-smash
        ./configure --extra-cflags=-I../obuparse --extra-ldflags=-L../obuparse
        make
    - name: Create archive
      run: |
        cd ${{ github.workspace }}/l-smash/cli
        zip L-SMASH_rev${{ steps.rev.outputs.REV_LIST_COUNT }}_macos_x64_${{ matrix.author }} LICENSE muxer remuxer boxdumper timelineeditor
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: l-smash-mac-${{ matrix.author }}
        path: ${{ github.workspace }}/l-smash/cli/L-SMASH_rev${{ steps.rev.outputs.REV_LIST_COUNT }}_macos_x64_${{ matrix.author }}.zip
      
      
  create_release:
    name: Create release
    needs: [linux-build,win-build,mac-build]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Get Date
      id: get_date
      run: |
        DATE_TIME=`date +'%Y-%m-%d-%H-%M-%S'`
        echo "DATE_TIME=${DATE_TIME}" >> $GITHUB_OUTPUT

    # https://gist.github.com/superbrothers/af84a2f8af394a62352e06537a640746        
    - name: Create a Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        RELEASE_NAME=Build-${{ steps.get_date.outputs.DATE_TIME }}
        TAG_NAME=build-${{ steps.get_date.outputs.DATE_TIME }}
        gh release create "${TAG_NAME}" ${{ github.workspace }}/artifacts/*/*.zip -t "${RELEASE_NAME}" 
        
    - uses: dev-drprasad/delete-older-releases@v0.3.3
      with:
        keep_latest: 20
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
