name: Build L-SMASH

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  win-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        config: 
          - { cpu: i686, arch: x86 }
          - { cpu: x86_64, arch: x64 }
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Checkout L-SMASH repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: l-smash/l-smash
        path: l-smash
    - name: Set REV_LIST_COUNT
      id: rev
      run: |
        cd ${{ github.workspace }}/l-smash
        REVCOUNT=`git rev-list --count HEAD`
        echo "::set-output name=REV_LIST_COUNT::${REVCOUNT}"
    - name: move LICENSE file
      run: |
        cd ${{ github.workspace }}/l-smash
        mv LICENSE cli
    - name: Install mingw-w64
      run: sudo apt install mingw-w64
    - name: Build
      run: |
        cd ${{ github.workspace }}/l-smash
        ./configure --cross-prefix=${{ matrix.config.cpu }}-w64-mingw32-
        make
    - name: Create archive
      run: |
        cd ${{ github.workspace }}/l-smash/cli
        zip L-SMASH_rev${{ steps.rev.outputs.REV_LIST_COUNT }}_win_${{ matrix.config.arch }} LICENSE muxer.exe remuxer.exe boxdumper.exe timelineeditor.exe
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: l-smash
        path: ${{ github.workspace }}/l-smash/cli/L-SMASH_rev${{ steps.rev.outputs.REV_LIST_COUNT }}_win_${{ matrix.config.arch }}.zip
    
  linux-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        config: 
          - { option: -m32, arch: x86 }
          - { option: -m64, arch: x64 }
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Checkout L-SMASH repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: l-smash/l-smash
        path: l-smash
    - name: Set REV_LIST_COUNT
      id: rev
      run: |
        cd ${{ github.workspace }}/l-smash
        REVCOUNT=`git rev-list --count HEAD`
        echo "::set-output name=REV_LIST_COUNT::${REVCOUNT}"
    - name: move LICENSE file
      run: |
        cd ${{ github.workspace }}/l-smash
        mv LICENSE cli
    - name: Install multilib
      run: |
        sudo apt update
        sudo apt install gcc-multilib
    - name: Build
      run: |
        cd ${{ github.workspace }}/l-smash
        ./configure --extra-cflags=${{ matrix.config.option }}
        make
    - name: Create archive
      run: |
        cd ${{ github.workspace }}/l-smash/cli
        zip L-SMASH_rev${{ steps.rev.outputs.REV_LIST_COUNT }}_linux_${{ matrix.config.arch }} LICENSE muxer remuxer boxdumper timelineeditor
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: l-smash
        path: ${{ github.workspace }}/l-smash/cli/L-SMASH_rev${{ steps.rev.outputs.REV_LIST_COUNT }}_linux_${{ matrix.config.arch }}.zip

  mac-build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Checkout L-SMASH repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: l-smash/l-smash
        path: l-smash
    - name: Set REV_LIST_COUNT
      id: rev
      run: |
        cd ${{ github.workspace }}/l-smash
        REVCOUNT=`git rev-list --count HEAD`
        echo "::set-output name=REV_LIST_COUNT::${REVCOUNT}"
    - name: move LICENSE file
      run: |
        cd ${{ github.workspace }}/l-smash
        mv LICENSE cli
    - name: Build
      run: |
        cd ${{ github.workspace }}/l-smash
        make
    - name: Create archive
      run: |
        cd ${{ github.workspace }}/l-smash/cli
        zip L-SMASH_rev${{ steps.rev.outputs.REV_LIST_COUNT }}_macos_x64 LICENSE muxer remuxer boxdumper timelineeditor
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: l-smash
        path: ${{ github.workspace }}/l-smash/cli/L-SMASH_rev${{ steps.rev.outputs.REV_LIST_COUNT }}_macos_x64.zip
      
      
  create_release:
    name: Create release
    needs: [linux-build,win-build,mac-build]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - uses: actions/download-artifact@v2
      with:
        name: l-smash
        path: artifacts
    
    - name: Get Date
      id: get_date
      run: |
        DATE_TIME=`date +'%Y-%m-%d-%H-%M-%S'`
        echo "::set-output name=DATE_TIME::${DATE_TIME}"

    # https://gist.github.com/superbrothers/af84a2f8af394a62352e06537a640746        
    - name: Create a Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        RELEASE_NAME=Build-${{ steps.get_date.outputs.DATE_TIME }}
        TAG_NAME=build-${{ steps.get_date.outputs.DATE_TIME }}
        assets=()
        for asset in ${{ github.workspace }}/artifacts/*.zip; do
          assets+=("-a" "$asset")
        done
        hub release create "${assets[@]}" -m "$RELEASE_NAME" "$TAG_NAME"
